output_root: '../src'
pytorch_data_dir: '/home/endrit/geo-scene/data'
results_dir: '/home/endrit/geo-scene/results/predictions/'
experiment_name: "cityscapes"
clustering_algorithm: "dbscan"
epsilon: 600 #used if dbscan is the clustering algorithm
min_samples: 55 #used if dbscan is the clustering algorithm
res: 320
batch_size: 1
num_workers: 1
eval_N_M: True
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False
InstanceClasses: ['car','ground']
resize_to_original: False
resize_res: 1024

model_paths:
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"
  - "checkpoints/saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
