output_root: '../'
pytorch_data_dir: 'dataset'
experiment_name: "Cityscapes"
res: 320
batch_size: 1
num_workers: 0
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False
InstanceClasses: [
            'road', 'sidewalk', 'parking', 'rail track', 'building',
            'wall', 'fence', 'guard rail', 'bridge', 'tunnel',
            'pole', 'polegroup', 'traffic light', 'traffic sign', 'vegetation',
            'terrain', 'sky', 'person', 'rider', 'car',
            'truck', 'bus', 'caravan', 'trailer', 'train',
            'motorcycle', 'bicycle']

model_paths:
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"
  - "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
